const Sequelize = require('sequelize');
const sequelize = require('../util/database');

//id (mongo autogenerated),name (string),attacks (array of strings e.g.: [‘Feint Attack’, ‘Doom News’]),abilities (array of strings),image (string, url to image)

const Pokemon = sequelize.define('user', {
    id: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true
    },
    name : Sequelize.STRING,
    attacks : {
       type:  Sequelize.ARRAY(Sequelize.STRING(100)),
       allowNull: false
    },
    abilities : {
        type:  Sequelize.ARRAY(Sequelize.STRING(100)),
        allowNull: false
     },
     image : Sequelize.STRING
})

module.exports = Pokemon;